"use client";
import {useEffect,useState} from 'react';
import {PlatformNav} from '@/components/platform/platform-nav';
import {authFetch} from '@/lib/auth-fetch';
type Data={labs:{id:string;name:string}[];developers:{id:string;name:string;email:string}[];policies:{labId:string;enabled:boolean;retentionDays:number;expiresAt:string|null}[];grants:{userId:string;canReadContent:boolean;canExport:boolean;labIds:string}[]};
const field='w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm';
export default function Settings(){const [data,setData]=useState<Data|null>(null);const [lab,setLab]=useState('');const [enabled,setEnabled]=useState(false);const [days,setDays]=useState(30);const [end,setEnd]=useState('');const [notice,setNotice]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [busy,setBusy]=useState(false);const [user,setUser]=useState('');const [grantEnabled,setGrantEnabled]=useState(true);const [content,setContent]=useState(false);const [exportAllowed,setExportAllowed]=useState(false);const [scope,setScope]=useState<string[]>([]);
 async function load(){const r=await authFetch('/api/platform/assistant-settings');const d=await r.json();if(!r.ok)throw new Error(d.error||'加载失败');setData(d);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function save(body:unknown){setBusy(true);setError('');setSuccess('');try{const r=await authFetch('/api/platform/assistant-settings',{method:'PUT',body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setSuccess('配置已保存并记录审计。');}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl"><PlatformNav active="settings"/><h1 className="text-3xl font-semibold">诊断采集与开发者权限</h1><p className="my-3 text-sm text-slate-500">默认只记录运行指标。完整内容只对指定实验室在测试窗口内开启，历史未采集内容无法补录。</p>{error&&<p role="alert" className="my-3 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}{success&&<p role="status" className="my-3 rounded-xl bg-teal-50 p-3 text-teal-800">{success}</p>}
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-lg font-semibold">测试实验室采集</h2><label className="block text-sm">实验室<select className={`${field} mt-2`} value={lab} onChange={e=>{setLab(e.target.value);const p=data?.policies.find(p=>p.labId===e.target.value);setEnabled(p?.enabled??false);setDays(p?.retentionDays??30);const dt=p?.expiresAt?new Date(p.expiresAt):new Date(Date.now()+7*86400000);setEnd(new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16));setNotice(false);}}><option value="">选择实验室</option>{data?.labs.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>采集完整问答、实际上下文与工具输入/输出</label><label className="block text-sm">测试窗口结束时间<input className={`${field} mt-2`} type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="block text-sm">新运行的内容保留天数（1–90）<input className={`${field} mt-2`} type="number" min={1} max={90} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={notice} onChange={e=>setNotice(e.target.checked)}/>已告知该实验室测试成员采集范围及用途</label><p className="text-xs leading-6 text-slate-500">开启后对话框显示测试提示。关闭或到期后，新运行只记指标；已有内容按创建时的保留期限清理。删除会话后立即禁止读取，后台每 10 分钟清理诊断正文。备份按运维保留策略处理。</p><button disabled={busy||!lab} className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm text-white disabled:opacity-40" onClick={()=>void save({kind:'policy',labId:lab,enabled,retentionDays:days,expiresAt:end?new Date(end).toISOString():null,noticeAcknowledged:notice})}>保存采集策略</button></section>
 <section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-lg font-semibold">开发者诊断授权</h2><p className="text-xs text-slate-500">仅有效的平台开发者可获得诊断权限，普通用户和实验室管理员始终无法访问。</p><label className="block text-sm">开发者<select className={`${field} mt-2`} value={user} onChange={e=>{setUser(e.target.value);const g=data?.grants.find(g=>g.userId===e.target.value);setGrantEnabled(!!g);setContent(g?.canReadContent??false);setExportAllowed(g?.canExport??false);setScope(g?JSON.parse(g.labIds):[]);}}><option value="">选择开发者</option>{data?.developers.map(d=><option key={d.id} value={d.id}>{d.name} · {d.email}</option>)}</select></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={grantEnabled} onChange={e=>setGrantEnabled(e.target.checked)}/>允许检索运行指标</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={content} onChange={e=>setContent(e.target.checked)}/>允许读取已授权采集的正文和管理案例</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={exportAllowed} onChange={e=>setExportAllowed(e.target.checked)}/>允许导出（同时需要正文权限）</label><label className="block text-sm">实验室范围（不选表示所有实验室）<select multiple className={`${field} mt-2 h-36`} value={scope} onChange={e=>setScope(Array.from(e.target.selectedOptions,o=>o.value))}>{data?.labs.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button disabled={busy||!user} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm text-white disabled:opacity-40" onClick={()=>void save({kind:'grant',userId:user,enabled:grantEnabled,canReadContent:content,canExport:exportAllowed,labIds:scope})}>保存开发者授权</button></section></div></div></main>;
}
