"use client";
import { useEffect, useState } from 'react';
import { Modal } from '@arco-design/web-react';
import { structureImageUrl } from '@/lib/assistant-markup';
import { authFetch } from '@/lib/auth-fetch';

export function StructureCard({ smiles, name = '分子结构' }: { smiles: string; name?: string }) {
  const [source, setSource] = useState('');
  const [error, setError] = useState('');
  const [attempt, setAttempt] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    let objectUrl = '';
    setSource(''); setError(''); setCopied(false);
    async function render() {
      try {
        if (!smiles || smiles.length > 2000) throw new Error('SMILES 为空或超过 2000 字符');
        const response = await authFetch(structureImageUrl(smiles), { signal: controller.signal });
        if (!response.ok) {
          const result = await response.json().catch(() => ({}));
          throw new Error(response.status === 401 ? '请登录后重试' : response.status === 429 ? '图片请求较多，请稍后重试' : result.error || '结构图片暂时无法加载');
        }
        const blob = await response.blob();
        if (controller.signal.aborted) return;
        objectUrl = URL.createObjectURL(blob); setSource(objectUrl);
      } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : '结构图片加载失败'); }
    }
    void render();
    return () => { controller.abort(); if (objectUrl) URL.revokeObjectURL(objectUrl); };
  }, [smiles, attempt]);
  const image = (large = false) => (
    // SVG is generated by RDKit, displayed as an image, never inserted as executable HTML.
    // eslint-disable-next-line @next/next/no-img-element
    <img src={source} alt={name} width={600} height={400} onError={() => setError('浏览器未能显示结构图片，请重试')} className={large ? 'h-auto max-h-[70vh] w-full object-contain' : 'h-auto w-full object-contain'} />
  );
  return <span className="my-3 inline-flex w-full max-w-[360px] flex-col overflow-hidden rounded-xl border border-gray-200 bg-white align-top text-gray-800" style={{ whiteSpace: 'normal' }}>
    <span className="flex items-center justify-between border-b border-gray-100 px-3 py-2 text-xs"><strong>{name}</strong><span>二维结构</span></span>
    {error ? <span role="alert" className="p-4 text-sm text-rose-700">{error}<button type="button" onClick={() => setAttempt(n => n + 1)} className="ml-2 underline">重试</button></span> : source ? <button type="button" aria-label={`放大${name}`} title="点击放大结构" onClick={() => setExpanded(true)}>{image()}</button> : <span role="status" className="flex min-h-40 items-center justify-center text-sm text-gray-500">正在绘制结构…</span>}
    <span className="border-t border-gray-100 p-3 text-xs"><code className="block break-all">{smiles}</code><button type="button" className="mt-2 text-teal-700 underline" onClick={async () => { try { await navigator.clipboard.writeText(smiles); setCopied(true); } catch { setCopied(false); } }}>{copied ? '已复制' : '复制 SMILES'}</button></span>
    <Modal visible={expanded} title={name} footer={null} onCancel={() => setExpanded(false)} style={{ width: 'min(850px, 94vw)' }} wrapStyle={{ zIndex: 10050 }}>{source && image(true)}<p className="mt-3 break-all text-xs">{smiles}</p></Modal>
  </span>;
}
