'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, Code2, Eye, EyeOff, Loader2, ShieldCheck } from 'lucide-react';
import { useAuthStore } from '@/store/auth-store';

export default function DeveloperLoginPage() {
  const router=useRouter(); const login=useAuthStore(s=>s.login); const user=useAuthStore(s=>s.user);
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{if(user?.platformRole==='PLATFORM_ADMIN')router.replace('/platform');},[router,user]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/auth/developer-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok)throw new Error(body.error||'登录失败');login(body.user);router.replace('/platform');}catch(e){setError(e instanceof Error?e.message:'登录失败');}finally{setBusy(false);}}
  return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#050914] px-5 py-10 text-slate-200"><div className="absolute left-1/2 top-1/2 size-[38rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-500/10 blur-[130px]"/><section className="relative w-full max-w-md rounded-[30px] border border-white/10 bg-[#0a121e]/95 p-6 shadow-2xl sm:p-9"><Link href="/login" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-violet-300"><ArrowLeft className="size-4"/>返回普通登录</Link><div className="mt-7 flex size-13 items-center justify-center rounded-2xl bg-violet-300 text-violet-950"><Code2 className="size-6"/></div><p className="mt-6 text-xs font-semibold uppercase tracking-[.22em] text-violet-300">Platform developer</p><h1 className="mt-2 text-2xl font-semibold text-white">开发者控制台登录</h1><p className="mt-3 text-sm leading-6 text-slate-500">仅接受由服务器初始化的 PLATFORM_ADMIN 账号。公开注册账号无法从此入口提权。</p>{error&&<p className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><label><span className="mb-2 block text-sm text-slate-300">开发者邮箱</span><input required type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="h-12 w-full rounded-xl border border-white/10 bg-white/[.05] px-4 text-white outline-none focus:border-violet-300/60"/></label><label><span className="mb-2 block text-sm text-slate-300">开发者密码</span><div className="relative"><input required type={show?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-xl border border-white/10 bg-white/[.05] px-4 pr-12 text-white outline-none focus:border-violet-300/60"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'隐藏密码':'显示密码'} className="absolute right-1 top-1 flex size-10 items-center justify-center rounded-lg text-slate-500 hover:text-white">{show?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div></label><button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-violet-300 font-semibold text-violet-950 disabled:opacity-60">{busy?<Loader2 className="size-4 animate-spin"/>:<ArrowRight className="size-4"/>}{busy?'正在验证…':'进入平台控制台'}</button></form><p className="mt-5 flex items-center gap-2 text-xs text-slate-600"><ShieldCheck className="size-3.5"/>独立限流、失败锁定与 HttpOnly 会话保护</p></section></main>;
}
