"use client";
import { useCallback,useEffect,useState } from 'react';
import Link from 'next/link';
import { Search,ArrowUpRight,Activity,Clock3,Bug,MessagesSquare } from 'lucide-react';
import { PlatformNav } from '@/components/platform/platform-nav';
import { authFetch } from '@/lib/auth-fetch';
type Row={userName:string;labName:string;id:string;problemCode:string;userId:string;labId:string;release:string;model:string;status:string;durationMs:number|null;createdAt:string;captureContent:boolean;shared:boolean;purgedAt:string|null;message:{sessionId:string;feedback:string|null};badCase:{id:string;status:string;category:string}|null};
const field='min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none focus:border-teal-500';
export default function RunsPage(){
 const [rows,setRows]=useState<Row[]>([]);const [q,setQ]=useState('');const [labId,setLabId]=useState('');const [release,setRelease]=useState('');const [status,setStatus]=useState('');const [mode,setMode]=useState('all');const [cursor,setCursor]=useState<string|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async(filters:URLSearchParams,after?:string)=>{setBusy(true);setError('');try{if(after)filters.set('cursor',after);const r=await authFetch(`/api/platform/assistant-runs?${filters}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'加载失败');setRows(prev=>after?[...prev,...d.runs]:d.runs);setCursor(d.nextCursor);}catch(e){setError(e instanceof Error?e.message:'加载失败');}finally{setBusy(false);}},[]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setQ(p.get('q')??'');setLabId(p.get('labId')??'');void load(p);},[load]);
 function filters(){const p=new URLSearchParams({q,labId,release,status});if(mode==='cases')p.set('cases','1');if(mode==='slow')p.set('slow','1');return p;}
 return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl"><PlatformNav active="runs"/>
  <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal-700">Developer workspace</p><h1 className="mt-2 text-3xl font-semibold">会话与运行记录</h1><p className="mt-2 text-sm text-slate-500">从用户的问题编号出发，定位一次回答的上下文、工具调用和版本。</p></div><Link href="/platform/assistant-settings" className="rounded-xl border bg-white px-4 py-3 text-sm">管理采集与权限</Link></div>
  <form onSubmit={e=>{e.preventDefault();void load(filters());}} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="mb-2 block text-sm font-medium" htmlFor="problem-search">问题编号 / 会话 ID / 用户 ID / Case ID</label><div className="flex gap-2"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><input id="problem-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="粘贴用户提供的 LC-… 问题编号" className={`${field} w-full pl-10`}/></div><button disabled={busy} className="rounded-xl bg-teal-700 px-5 text-sm font-medium text-white disabled:opacity-50">{busy?'检索中…':'定位记录'}</button></div>
   <div className="mt-3 grid gap-3 sm:grid-cols-3"><input aria-label="实验室 ID" placeholder="实验室 ID（可从管理页进入）" value={labId} onChange={e=>setLabId(e.target.value)} className={field}/><input aria-label="版本" placeholder="版本 SHA" value={release} onChange={e=>setRelease(e.target.value)} className={field}/><select aria-label="运行状态" value={status} onChange={e=>setStatus(e.target.value)} className={field}><option value="">全部运行状态</option>{['OK','ERROR','CANCELLED','TRUNCATED','RUNNING'].map(s=><option key={s}>{s}</option>)}</select></div>
   <div className="mt-4 flex flex-wrap gap-2">{[['all','全部运行',Activity],['cases','已收集案例',Bug],['slow','慢请求 ≥30s',Clock3]] .map(([v,label,Icon])=>{const I=Icon as typeof Activity;return <button type="button" key={String(v)} onClick={()=>{setMode(String(v));const f=filters();f.delete('cases');f.delete('slow');if(v==='cases')f.set('cases','1');if(v==='slow')f.set('slow','1');void load(f);}} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${mode===v?'bg-teal-50 text-teal-800':'bg-slate-50 text-slate-500'}`}><I className="size-4"/>{String(label)}</button>;})}</div>
  </form>
  {error&&<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}
  <section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-semibold">运行列表</h2><span className="text-xs text-slate-500">已加载 {rows.length} 条</span></div>{!rows.length&&!busy&&<div className="p-12 text-center text-slate-500"><MessagesSquare className="mx-auto mb-3 size-8 text-slate-300"/><p>没有匹配的记录</p><p className="mt-2 text-xs">检查编号、筛选条件或诊断授权范围。新运行会自动记录基础指标。</p></div>}
  <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{['问题 / 时间','用户 / 实验室','版本 / 模型','状态 / 耗时','反馈 / 采集','操作'].map(h=><th key={h} className="p-4 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="p-4"><p title={r.problemCode} className="max-w-44 truncate font-mono text-xs">{r.problemCode}</p><p className="mt-1 text-xs text-slate-400">{new Date(r.createdAt).toLocaleString()}</p></td><td className="p-4"><p title={r.userId} className="max-w-36 truncate text-xs">{r.userName}</p><p title={r.labId} className="mt-1 max-w-36 truncate text-xs text-slate-400">{r.labName}</p></td><td className="p-4"><p className="font-mono text-xs">{r.release.slice(0,12)}</p><p className="mt-1 text-xs text-slate-500">{r.model}</p></td><td className="p-4"><span className={`rounded px-2 py-1 text-xs ${r.status==='OK'?'bg-emerald-50 text-emerald-700':r.status==='ERROR'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'}`}>{r.status}</span><p className="mt-2 text-xs text-slate-500">{r.durationMs===null?'进行中':`${(r.durationMs/1000).toFixed(1)} s`}</p></td><td className="p-4 text-xs"><p>{r.message.feedback==='useful'?'有帮助':r.message.feedback==='not_useful'?'没帮助':'未反馈'}{r.badCase?' · Case':''}</p><p className="mt-1 text-slate-400">{r.purgedAt?'内容已清理':r.captureContent?'测试采集':r.shared?'用户共享':'仅指标'}</p></td><td className="p-4"><Link className="inline-flex items-center gap-1 text-teal-700" href={`/platform/assistant-cases?run=${encodeURIComponent(r.id)}`}>诊断<ArrowUpRight className="size-4"/></Link></td></tr>)}</tbody></table></div></section>
  {cursor&&<button disabled={busy} className="mt-4 rounded-xl border bg-white px-4 py-2 text-sm" onClick={()=>void load(filters(),cursor)}>加载更多</button>}
 </div></main>;
}
