'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, Clock3, X } from 'lucide-react';
import { useAuthStore } from '@/store/auth-store';

type Application = { id: string; requestedLabRole: string; submittedAt: string; formSnapshot: { message?: string }; applicant: { name: string; email: string; phone: string | null; institutionType: string; schoolName: string | null; collegeName: string | null; academicIdentity: string | null; companyName: string | null; companyIdentity: string | null } };

export default function LabApplicationsPage() {
  const role=useAuthStore(s=>s.user?.labRole); const [items,setItems]=useState<Application[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
  const load=useCallback(async()=>{const r=await fetch('/api/labs/applications');const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.data)},[]);
  useEffect(()=>{void load().catch(e=>setError(e.message))},[load]);
  async function review(id:string,action:'APPROVE'|'REJECT'){const comment=window.prompt(action==='REJECT'?'请输入拒绝原因':'审批备注（可选）')||'';setBusy(id);try{const r=await fetch(`/api/labs/applications/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,comment})});const b=await r.json();if(!r.ok)throw new Error(b.error);await load()}catch(e){setError(e instanceof Error?e.message:'审批失败')}finally{setBusy('')}}
  return <div className="mx-auto max-w-5xl space-y-5 p-5 sm:p-7"><Link href="/admin/members" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-teal-700"><ArrowLeft className="size-4"/>成员管理</Link><div><h1 className="text-2xl font-semibold text-slate-900">新账号审批</h1><p className="mt-1 text-sm text-slate-500">仅 LAB_OWNER 可批准本实验室的 LAB_ADMIN 与 LAB_MEMBER。</p></div>{role!=='LAB_OWNER'&&<p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">当前账号不是 LAB_OWNER，无法访问审批数据。</p>}{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="space-y-3">{items.length===0?<div className="rounded-2xl border border-dashed border-slate-200 bg-white p-12 text-center text-sm text-slate-400"><Clock3 className="mx-auto mb-3"/>没有待审批申请</div>:items.map(item=><article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 md:flex-row md:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-semibold text-slate-900">{item.applicant.name}</h2><span className="rounded-full bg-teal-50 px-2 py-1 text-xs text-teal-700">{item.requestedLabRole}</span></div><p className="mt-1 text-sm text-slate-500">{item.applicant.email} · {item.applicant.phone}</p><p className="mt-3 text-sm text-slate-600">{item.applicant.institutionType==='UNIVERSITY'?`${item.applicant.schoolName} · ${item.applicant.collegeName} · ${item.applicant.academicIdentity}`:`${item.applicant.companyName} · ${item.applicant.companyIdentity}`}</p>{item.formSnapshot?.message&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm text-slate-500">{item.formSnapshot.message}</p>}</div><div className="flex shrink-0 gap-2"><button disabled={busy===item.id} onClick={()=>void review(item.id,'REJECT')} className="flex h-10 items-center gap-2 rounded-xl border border-red-200 px-4 text-sm text-red-600"><X className="size-4"/>拒绝</button><button disabled={busy===item.id} onClick={()=>void review(item.id,'APPROVE')} className="flex h-10 items-center gap-2 rounded-xl bg-teal-600 px-4 text-sm text-white"><Check className="size-4"/>批准</button></div></div></article>)}</section></div>;
}
